// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	pkg "github.com/Avepa/booking/pkg"
	gomock "github.com/golang/mock/gomock"
)

// MockRoom is a mock of Room interface.
type MockRoom struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMockRecorder
}

// MockRoomMockRecorder is the mock recorder for MockRoom.
type MockRoomMockRecorder struct {
	mock *MockRoom
}

// NewMockRoom creates a new mock instance.
func NewMockRoom(ctrl *gomock.Controller) *MockRoom {
	mock := &MockRoom{ctrl: ctrl}
	mock.recorder = &MockRoomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoom) EXPECT() *MockRoomMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRoom) Add(room *pkg.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRoomMockRecorder) Add(room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRoom)(nil).Add), room)
}

// Delete mocks base method.
func (m *MockRoom) Delete(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoomMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoom)(nil).Delete), id)
}

// GetByDate mocks base method.
func (m *MockRoom) GetByDate() ([]pkg.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDate")
	ret0, _ := ret[0].([]pkg.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDate indicates an expected call of GetByDate.
func (mr *MockRoomMockRecorder) GetByDate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDate", reflect.TypeOf((*MockRoom)(nil).GetByDate))
}

// GetByDateDESC mocks base method.
func (m *MockRoom) GetByDateDESC() ([]pkg.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDateDESC")
	ret0, _ := ret[0].([]pkg.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDateDESC indicates an expected call of GetByDateDESC.
func (mr *MockRoomMockRecorder) GetByDateDESC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDateDESC", reflect.TypeOf((*MockRoom)(nil).GetByDateDESC))
}

// GetByPrice mocks base method.
func (m *MockRoom) GetByPrice() ([]pkg.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPrice")
	ret0, _ := ret[0].([]pkg.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPrice indicates an expected call of GetByPrice.
func (mr *MockRoomMockRecorder) GetByPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPrice", reflect.TypeOf((*MockRoom)(nil).GetByPrice))
}

// GetByPriceDESC mocks base method.
func (m *MockRoom) GetByPriceDESC() ([]pkg.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPriceDESC")
	ret0, _ := ret[0].([]pkg.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPriceDESC indicates an expected call of GetByPriceDESC.
func (mr *MockRoomMockRecorder) GetByPriceDESC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPriceDESC", reflect.TypeOf((*MockRoom)(nil).GetByPriceDESC))
}

// MockBookings is a mock of Bookings interface.
type MockBookings struct {
	ctrl     *gomock.Controller
	recorder *MockBookingsMockRecorder
}

// MockBookingsMockRecorder is the mock recorder for MockBookings.
type MockBookingsMockRecorder struct {
	mock *MockBookings
}

// NewMockBookings creates a new mock instance.
func NewMockBookings(ctrl *gomock.Controller) *MockBookings {
	mock := &MockBookings{ctrl: ctrl}
	mock.recorder = &MockBookingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookings) EXPECT() *MockBookingsMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBookings) Add(room int64, bookings *pkg.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", room, bookings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockBookingsMockRecorder) Add(room, bookings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBookings)(nil).Add), room, bookings)
}

// Delete mocks base method.
func (m *MockBookings) Delete(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBookingsMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookings)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockBookings) Get(id int64) ([]pkg.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].([]pkg.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBookingsMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBookings)(nil).Get), id)
}
